name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  lint_pr:
    name: Lint PR
    uses: cumbucadev/shared-workflows/.github/workflows/semantic-pull-request/v1/semantic-pull-request.yml@main
